### ISSUE TITLE
Insecure Password Handling

### ISSUE THREAD

**Issue by soatok** [olyckne/effy#1]
1. https://github.com/olyckne/effy/blob/eeefa705be60b282ea12ed79bdfc54f1a6ff251c/system/models/User_model.php#L131 - bad password verification

2. https://github.com/olyckne/effy/blob/eeefa705be60b282ea12ed79bdfc54f1a6ff251c/system/models/User_model.php#L224-L236 - insecure randomness for salt generation

For the first issue, see: [How to Safely Store a Password in 2016](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016#php) (still relevant in 2017). For consequences of how this can fail:

* https://security.stackexchange.com/a/61387
* https://www.whitehatsec.com/blog/magic-hashes/
* https://natmchugh.blogspot.com/2015/02/create-your-own-md5-collisions.html

For the second, [generating secure randomness in PHP](https://paragonie.com/blog/2016/05/how-generate-secure-random-numbers-in-various-programming-languages#php-csprng).

**Comment by olyckne** [comment]
So... this is a school project I did 6 years ago ¯\_(ツ)_/¯
